-- Sorting using the column number
SELECT LAST_NAME, JOB_ID, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
ORDER BY 2 ASC, 3 DESC;


-- Summing the salary by department using the GROUP BY clause
SELECT DEPARTMENT_ID, SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;


-- Using the HAVING clause
SELECT DEPARTMENT_ID, MAX(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING MAX(SALARY) > 10000;


-- Summing only DISTINCT salaries
SELECT DEPARTMENT_ID, SUM(DISTINCT SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;


-- LISTAGG example
SELECT LISTAGG(DEPARTMENT_ID, ' = ')
FROM EMPLOYEES;


-- ROWNUM EXAMPLE
SELECT
    DEPARTMENT_ID
FROM
    EMPLOYEES
WHERE
    ROWNUM >= 5;


SELECT
    DEPARTMENT_ID
FROM (
    SELECT 
        DEPARTMENT_ID,
        ROWNUM AS RNUM
    FROM
        EMPLOYEES
    )
WHERE
    RNUM >= 5;


SELECT
    *
FROM
    EMPLOYEES
WHERE
    ROWNUM = 1
ORDER BY
    DBMS_RANDOM.VALUE();


SELECT * FROM (
    SELECT *
    FROM EMPLOYEES
    ORDER BY DBMS_RANDOM.VALUE()
) WHERE ROWNUM = 1;


-- FETCH instead
SELECT
    *
FROM
    EMPLOYEES
ORDER BY
    DBMS_RANDOM.VALUE()
FETCH FIRST ROW ONLY;

